// import p1_img from './product_1.png'
// import p2_img from './product_2.png'
// import p3_img from './product_3.png'
// import p4_img from './product_4.png'

export const data_product = [
  {
    id:1,
    name:"Extra Soft Touch Lamb Doll",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-12.jpg",
    category:"clothes",
    new_price:50.00,
    old_price:80.50,
  },
  {id:2,
    name:"Twin Cute Bunny Set Combo",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-11.jpg",
    category:"clothes",
    new_price:85.00,
    old_price:120.50,
  },
  {id:3,
    name:"Colorful Birdies on Orange Bandana",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-10.jpg",
    category:"clothes",
    new_price:60.00,
    old_price:100.50,
  },
  {id:4,
    name:"Sunny Outdoor Picnic Set Yellow",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-8.jpg",
    category:"clothes",
    new_price:100.00,
    old_price:150.00,
  },
  {id:5,
    name:"Sunny Outdoor Picnic Set Yellow",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-8.jpg",
    category:"clothes",
    new_price:100.00,
    old_price:150.00,
  },
  {
    id:1,
    name:"Extra Soft Touch Lamb Doll",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-12.jpg",
    category:"clothes",
    new_price:50.00,
    old_price:80.50,
  },
  {id:2,
    name:"Twin Cute Bunny Set Combo",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-11.jpg",
    category:"clothes",
    new_price:85.00,
    old_price:120.50,
  },
  {id:3,
    name:"Colorful Birdies on Orange Bandana",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-10.jpg",
    category:"clothes",
    new_price:60.00,
    old_price:100.50,
  },
  {id:4,
    name:"Sunny Outdoor Picnic Set Yellow",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-8.jpg",
    category:"clothes",
    new_price:100.00,
    old_price:150.00,
  },
  {id:5,
    name:"Sunny Outdoor Picnic Set Yellow",
    image:"https://websitedemos.net/baby-store-04/wp-content/uploads/sites/750/2020/12/baby-store-product-img-8.jpg",
    category:"clothes",
    new_price:100.00,
    old_price:150.00,
  },
];

export default data_product;
